# SIM (Sistema de Informações sobre Mortalidade)

https://pysus.readthedocs.io/en/latest/databases/SIM.html

----------------------------------------------------

# Instalando as bibliotecas:

In [ ]:
!pip install -U git+https://github.com/AlertaDengue/PySUS.git    # instala a versão mais recente

Collecting git+https://github.com/AlertaDengue/PySUS.git
  Cloning https://github.com/AlertaDengue/PySUS.git to /tmp/pip-req-build-clknoacd
  Running command git clone --filter=blob:none --quiet https://github.com/AlertaDengue/PySUS.git /tmp/pip-req-build-clknoacd
  Resolved https://github.com/AlertaDengue/PySUS.git to commit 54f7800db4da5171d55e3446d638d64beeb8b149
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting Unidecode<2.0.0,>=1.3.6 (from pysus==0.15.0)
  Downloading Unidecode-1.3.8-py3-none-any.whl.metadata (13 kB)
Collecting aioftp<0.22.0,>=0.21.4 (from pysus==0.15.0)
  Downloading aioftp-0.21.4-py3-none-any.whl.metadata (6.1 kB)
Collecting bigtree<0.13.0,>=0.12.2 (from pysus==0.15.0)
  Downloading bigtree-0.12.5-py3-none-any.whl.metadata (28 kB)
Collecting cffi==1.15.1 (from pysus==0.15.0)
  Downloading cffi-1.15.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.1 kB)
Collecting dateparser<2.0.0,>=1.1.8 (from pysus==0.15.0)
  Downloading dateparser-1.2.0-py2.py3-none-any.whl.metadata (28 kB)
Collecting dbfread==2.0.7 (from pysus==0.15.0)
  Downloading dbfread-2.0.7-py2.py3-none-any.whl.metadata (3.3 kB)
Collecting elasticsearch==7.16.2 (from elasticsearch[preprocessing]==7.16.2->pysus==0.15.0)
  Downloading elasticsearch-7.16.2-py2.py3-none-any.whl.metadata (5.7 kB)
Collecting fastparquet>=2023.10.1 (from pysus==0.15.0)
  Downloading fastparquet-2024.11.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.2 kB)
Requirement already satisfied: humanize<5.0.0,>=4.8.0 in /usr/local/lib/python3.10/dist-packages (from pysus==0.15.0) (4.11.0)
Collecting loguru<0.7.0,>=0.6.0 (from pysus==0.15.0)
  Downloading loguru-0.6.0-py3-none-any.whl.metadata (21 kB)
Collecting numpy==1.26.2 (from pysus==0.15.0)
  Downloading numpy-1.26.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.2/61.2 kB 3.4 MB/s eta 0:00:00
Requirement already satisfied: pandas<3.0.0,>=2.2.2 in /usr/local/lib/python3.10/dist-packages (from pysus==0.15.0) (2.2.2)
Requirement already satisfied: pyarrow>=11.0.0 in /usr/local/lib/python3.10/dist-packages (from pysus==0.15.0) (17.0.0)
Collecting pycparser==2.21 (from pysus==0.15.0)
  Downloading pycparser-2.21-py2.py3-none-any.whl.metadata (1.1 kB)
Collecting pyreaddbc>=1.1.0 (from pysus==0.15.0)
  Downloading pyreaddbc-1.2.0.tar.gz (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.7/57.7 kB 4.8 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: python-dateutil==2.8.2 in /usr/local/lib/python3.10/dist-packages (from pysus==0.15.0) (2.8.2)
Collecting tqdm==4.64.0 (from pysus==0.15.0)
  Downloading tqdm-4.64.0-py2.py3-none-any.whl.metadata (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.3/57.3 kB 3.8 MB/s eta 0:00:00
Requirement already satisfied: typing-extensions<5.0.0,>=4.9.0 in /usr/local/lib/python3.10/dist-packages (from pysus==0.15.0) (4.12.2)
Collecting urwid<3.0.0,>=2.1.2 (from pysus==0.15.0)
  Downloading urwid-2.6.16-py3-none-any.whl.metadata (11 kB)
Collecting wget<4.0,>=3.2 (from pysus==0.15.0)
  Downloading wget-3.2.zip (10 kB)
  Preparing metadata (setup.py) ... done
Collecting urllib3<2,>=1.21.1 (from elasticsearch==7.16.2->elasticsearch[preprocessing]==7.16.2->pysus==0.15.0)
  Downloading urllib3-1.26.20-py2.py3-none-any.whl.metadata (50 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.1/50.1 kB 3.8 MB/s eta 0:00:00
Requirement already satisfied: certifi in /usr/local/lib/python3.10/dist-packages (from elasticsearch==7.16.2->elasticsearch[preprocessing]==7.16.2->pysus==0.15.0) (2024.8.30)
WARNING: elasticsearch 7.16.2 does not provide the extra 'preprocessing'
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil==2.8.2->pysus==0.15.0) (1.16.0)
Requirement already satisfied: pytz in /usr/local/lib/python3.10/dist-packages (from dateparser<2.0.0,>=1.1.8->pysus==0.15.0) (2024.2)
Requirement already satisfied: regex!=2019.02.19,!=2021.8.27 in /usr/local/lib/python3.10/dist-packages (from dateparser<2.0.0,>=1.1.8->pysus==0.15.0) (2024.9.11)
Requirement already satisfied: tzlocal in /usr/local/lib/python3.10/dist-packages (from dateparser<2.0.0,>=1.1.8->pysus==0.15.0) (5.2)
Collecting cramjam>=2.3 (from fastparquet>=2023.10.1->pysus==0.15.0)
  Downloading cramjam-2.9.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from fastparquet>=2023.10.1->pysus==0.15.0) (2024.10.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from fastparquet>=2023.10.1->pysus==0.15.0) (24.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas<3.0.0,>=2.2.2->pysus==0.15.0) (2024.2)
Requirement already satisfied: pyyaml>=6 in /usr/local/lib/python3.10/dist-packages (from pyreaddbc>=1.1.0->pysus==0.15.0) (6.0.2)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.10/dist-packages (from urwid<3.0.0,>=2.1.2->pysus==0.15.0) (0.2.13)
Downloading cffi-1.15.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (441 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 441.8/441.8 kB 24.3 MB/s eta 0:00:00
Downloading dbfread-2.0.7-py2.py3-none-any.whl (20 kB)
Downloading elasticsearch-7.16.2-py2.py3-none-any.whl (385 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 385.7/385.7 kB 24.3 MB/s eta 0:00:00
Downloading numpy-1.26.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.2/18.2 MB 73.6 MB/s eta 0:00:00
Downloading pycparser-2.21-py2.py3-none-any.whl (118 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 118.7/118.7 kB 9.4 MB/s eta 0:00:00
Downloading tqdm-4.64.0-py2.py3-none-any.whl (78 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.4/78.4 kB 7.0 MB/s eta 0:00:00
Downloading aioftp-0.21.4-py3-none-any.whl (37 kB)
Downloading bigtree-0.12.5-py3-none-any.whl (63 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.5/63.5 kB 5.1 MB/s eta 0:00:00
Downloading dateparser-1.2.0-py2.py3-none-any.whl (294 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 295.0/295.0 kB 20.9 MB/s eta 0:00:00
Downloading fastparquet-2024.11.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 69.9 MB/s eta 0:00:00
Downloading loguru-0.6.0-py3-none-any.whl (58 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.3/58.3 kB 4.4 MB/s eta 0:00:00
Downloading Unidecode-1.3.8-py3-none-any.whl (235 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 235.5/235.5 kB 21.0 MB/s eta 0:00:00
Downloading urwid-2.6.16-py3-none-any.whl (297 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 297.2/297.2 kB 23.8 MB/s eta 0:00:00
Downloading cramjam-2.9.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 63.8 MB/s eta 0:00:00
Downloading urllib3-1.26.20-py2.py3-none-any.whl (144 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 144.2/144.2 kB 11.6 MB/s eta 0:00:00
Building wheels for collected packages: pysus, pyreaddbc, wget
  Building wheel for pysus (pyproject.toml) ... done
  Created wheel for pysus: filename=pysus-0.15.0-py3-none-any.whl size=1431968 sha256=818bf6108209805ed6f823bfb214202942e0a1d5b8de93f8c63b5a9a17e793d8
  Stored in directory: /tmp/pip-ephem-wheel-cache-ykza8da9/wheels/8a/d7/46/e8ca0ed9954b00155b8607fb9bef33a7e381b8f144a471a849
  Building wheel for pyreaddbc (pyproject.toml) ... done
  Created wheel for pyreaddbc: filename=pyreaddbc-1.2.0-cp310-cp310-manylinux_2_35_x86_64.whl size=89794 sha256=a1b8376988c96f1071c32c93cef2f2adfb487a1d668214114864fab1c2208440
  Stored in directory: /root/.cache/pip/wheels/44/9c/3c/0b2efbb6180556cf083065c5c0368bb38a26c83dbd5f9a9ba1
  Building wheel for wget (setup.py) ... done
  Created wheel for wget: filename=wget-3.2-py3-none-any.whl size=9656 sha256=e6995bf070f6be6a2673566bd82064959ec73fdd4367033df61ce23aa184ecf6
  Stored in directory: /root/.cache/pip/wheels/8b/f1/7f/5c94f0a7a505ca1c81cd1d9208ae2064675d97582078e6c769
Successfully built pysus pyreaddbc wget
Installing collected packages: wget, dbfread, urwid, urllib3, Unidecode, tqdm, pycparser, numpy, loguru, cramjam, bigtree, aioftp, elasticsearch, dateparser, cffi, pyreaddbc, fastparquet, pysus
  Attempting uninstall: urllib3
    Found existing installation: urllib3 2.2.3
    Uninstalling urllib3-2.2.3:
      Successfully uninstalled urllib3-2.2.3
  Attempting uninstall: tqdm
    Found existing installation: tqdm 4.66.6
    Uninstalling tqdm-4.66.6:
      Successfully uninstalled tqdm-4.66.6
  Attempting uninstall: pycparser
    Found existing installation: pycparser 2.22
    Uninstalling pycparser-2.22:
      Successfully uninstalled pycparser-2.22
  Attempting uninstall: numpy
    Found existing installation: numpy 1.26.4
    Uninstalling numpy-1.26.4:
      Successfully uninstalled numpy-1.26.4
  Attempting uninstall: cffi
    Found existing installation: cffi 1.17.1
    Uninstalling cffi-1.17.1:
      Successfully uninstalled cffi-1.17.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
dopamine-rl 4.0.9 requires tqdm>=4.64.1, but you have tqdm 4.64.0 which is incompatible.
pygit2 1.16.0 requires cffi>=1.17.0, but you have cffi 1.15.1 which is incompatible.
Successfully installed Unidecode-1.3.8 aioftp-0.21.4 bigtree-0.12.5 cffi-1.15.1 cramjam-2.9.0 dateparser-1.2.0 dbfread-2.0.7 elasticsearch-7.16.2 fastparquet-2024.11.0 loguru-0.6.0 numpy-1.26.2 pycparser-2.21 pyreaddbc-1.2.0 pysus-0.15.0 tqdm-4.64.0 urllib3-1.26.20 urwid-2.6.16 wget-3.2

https://pysus.readthedocs.io/en/latest/databases/SIM.html

In [ ]:
!pip install pysus

Requirement already satisfied: pysus in /usr/local/lib/python3.10/dist-packages (0.15.0)
Requirement already satisfied: Unidecode<2.0.0,>=1.3.6 in /usr/local/lib/python3.10/dist-packages (from pysus) (1.3.8)
Requirement already satisfied: aioftp<0.22.0,>=0.21.4 in /usr/local/lib/python3.10/dist-packages (from pysus) (0.21.4)
Requirement already satisfied: bigtree<0.13.0,>=0.12.2 in /usr/local/lib/python3.10/dist-packages (from pysus) (0.12.5)
Requirement already satisfied: cffi==1.15.1 in /usr/local/lib/python3.10/dist-packages (from pysus) (1.15.1)
Requirement already satisfied: dateparser<2.0.0,>=1.1.8 in /usr/local/lib/python3.10/dist-packages (from pysus) (1.2.0)
Requirement already satisfied: dbfread==2.0.7 in /usr/local/lib/python3.10/dist-packages (from pysus) (2.0.7)
Requirement already satisfied: elasticsearch==7.16.2 in /usr/local/lib/python3.10/dist-packages (from elasticsearch[preprocessing]==7.16.2->pysus) (7.16.2)
Requirement already satisfied: fastparquet>=2023.10.1 in /usr/local/lib/python3.10/dist-packages (from pysus) (2024.11.0)
Requirement already satisfied: humanize<5.0.0,>=4.8.0 in /usr/local/lib/python3.10/dist-packages (from pysus) (4.11.0)
Requirement already satisfied: loguru<0.7.0,>=0.6.0 in /usr/local/lib/python3.10/dist-packages (from pysus) (0.6.0)
Requirement already satisfied: numpy==1.26.2 in /usr/local/lib/python3.10/dist-packages (from pysus) (1.26.2)
Requirement already satisfied: pandas<3.0.0,>=2.2.2 in /usr/local/lib/python3.10/dist-packages (from pysus) (2.2.2)
Requirement already satisfied: pyarrow>=11.0.0 in /usr/local/lib/python3.10/dist-packages (from pysus) (17.0.0)
Requirement already satisfied: pycparser==2.21 in /usr/local/lib/python3.10/dist-packages (from pysus) (2.21)
Requirement already satisfied: pyreaddbc>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from pysus) (1.2.0)
Requirement already satisfied: python-dateutil==2.8.2 in /usr/local/lib/python3.10/dist-packages (from pysus) (2.8.2)
Requirement already satisfied: tqdm==4.64.0 in /usr/local/lib/python3.10/dist-packages (from pysus) (4.64.0)
Requirement already satisfied: typing-extensions<5.0.0,>=4.9.0 in /usr/local/lib/python3.10/dist-packages (from pysus) (4.12.2)
Requirement already satisfied: urwid<3.0.0,>=2.1.2 in /usr/local/lib/python3.10/dist-packages (from pysus) (2.6.16)
Requirement already satisfied: wget<4.0,>=3.2 in /usr/local/lib/python3.10/dist-packages (from pysus) (3.2)
Requirement already satisfied: urllib3<2,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from elasticsearch==7.16.2->elasticsearch[preprocessing]==7.16.2->pysus) (1.26.20)
Requirement already satisfied: certifi in /usr/local/lib/python3.10/dist-packages (from elasticsearch==7.16.2->elasticsearch[preprocessing]==7.16.2->pysus) (2024.8.30)
WARNING: elasticsearch 7.16.2 does not provide the extra 'preprocessing'
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil==2.8.2->pysus) (1.16.0)
Requirement already satisfied: pytz in /usr/local/lib/python3.10/dist-packages (from dateparser<2.0.0,>=1.1.8->pysus) (2024.2)
Requirement already satisfied: regex!=2019.02.19,!=2021.8.27 in /usr/local/lib/python3.10/dist-packages (from dateparser<2.0.0,>=1.1.8->pysus) (2024.9.11)
Requirement already satisfied: tzlocal in /usr/local/lib/python3.10/dist-packages (from dateparser<2.0.0,>=1.1.8->pysus) (5.2)
Requirement already satisfied: cramjam>=2.3 in /usr/local/lib/python3.10/dist-packages (from fastparquet>=2023.10.1->pysus) (2.9.0)
Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from fastparquet>=2023.10.1->pysus) (2024.10.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from fastparquet>=2023.10.1->pysus) (24.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas<3.0.0,>=2.2.2->pysus) (2024.2)
Requirement already satisfied: pyyaml>=6 in /usr/local/lib/python3.10/dist-packages (from pyreaddbc>=1.1.0->pysus) (6.0.2)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.10/dist-packages (from urwid<3.0.0,>=2.1.2->pysus) (0.2.13)

In [ ]:
from pysus import SIM

In [ ]:
import pandas as pd
from pandas import DataFrame
from pandas import concat

------------------------

# SIM FTP Database

# Sistema de Informação sobre Mortalidade

In [ ]:
sim = SIM().load() # Loads the files from DATASUS

In [ ]:
sim.metadata

{'long_name': 'Sistema de Informação sobre Mortalidade',
 'source': 'http://sim.saude.gov.br',
 'description': ''}

In [ ]:
sim.groups

{'CID10': 'DO', 'CID9': 'DOR'}

In [ ]:
sim.paths

(/dissemin/publicos/SIM/CID10/DORES, /dissemin/publicos/SIM/CID9/DORES)

Para mais informações sobre CID9 e CID10:

http://tabnet.saude.es.gov.br/cgi/tabnet/sim/sim96/obtdescr.htm

----------------------------------------------------

# Pegando arquivos específicos:

Dados até 1995 só podem ser recuperados pela CID-9.

Dados de 1996 em diante só podem ser recuperados pela CID-10.

In [ ]:
sim.get_files("CID10", uf=["SP", "RJ"], year=[2019, 2020, 2021])

[DORJ2019.dbc,
 DORJ2020.dbc,
 DORJ2021.dbc,
 DOSP2019.dbc,
 DOSP2020.dbc,
 DOSP2021.dbc]

In [ ]:
sim.get_files("CID10", uf="GO", year=2023)

[]

In [ ]:
sim.get_files("CID10", uf="GO", year=2022)

[DOGO2022.dbc]

In [ ]:
arquivos = sim.get_files(["CID9", "CID10"], uf=["SP"], year=[1995, 2020])
sp_cid9, sp_cid10 = arquivos
sim.describe(sp_cid9)

{'name': 'DORSP95.DBC',
 'uf': 'São Paulo',
 'year': 1995,
 'group': 'CID9',
 'size': '8.2 MB',
 'last_update': '2020-01-31 02:48PM'}

In [ ]:
sim.describe(sp_cid10)

{'name': 'DOSP2020.dbc',
 'uf': 'São Paulo',
 'year': 2020,
 'group': 'CID10',
 'size': '28.7 MB',
 'last_update': '2022-03-31 04:19PM'}

In [ ]:
arquivos = sim.get_files(["CID10"], uf=["GO"], year=[2022])

In [ ]:
arquivos

[DOGO2022.dbc]

In [ ]:
sim.describe(arquivos[0])

{'name': 'DOGO2022.dbc',
 'uf': 'Goiás',
 'year': 2022,
 'group': 'CID10',
 'size': '4.4 MB',
 'last_update': '2023-12-21 04:19PM'}

----------------------------------------------------

# Downloading files

In [ ]:
parquet = sim.download(arquivos)

DOGO2022.parquet: 100%|██████████| 116k/116k [00:08<00:00, 13.9kB/s]

In [ ]:
parquet

/root/pysus/DOGO2022.parquet

----------------------------------------------------

# Reading files

PySUS uses Parquets as output, use the method to_dataframe() to read the file as pandas DataFrame

In [ ]:
parquet.to_dataframe()

,ORIGEM,TIPOBITO,DTOBITO,HORAOBITO,NATURAL,CODMUNNATU,DTNASC,IDADE,SEXO,RACACOR,...,FONTES,TPRESGINFO,TPNIVELINV,NUDIASINF,DTCADINF,MORTEPARTO,DTCONCASO,FONTESINF,ALTCAUSA,CONTADOR
0,1,2,02112022,0350,822,220170,20101940,482,1,4,...,,,,,,,,,,1024530
1,1,2,30112022,0415,831,311370,09041939,483,2,1,...,,,,,,,,,,1024531
2,1,2,23102022,1340,852,520870,15071972,450,1,4,...,,,,,,,,,,1024532
3,1,2,02112022,1421,835,350780,12101932,490,1,1,...,,,,,,,,,,1024533
4,1,2,30102022,1735,852,520870,18061962,460,1,4,...,,,,,,,,,,1024547
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47265,1,2,27112022,0002,822,220360,15061937,485,2,4,...,,,,,,,,,,1024525
47266,1,2,20102022,2100,852,521740,28011950,472,1,1,...,,,,,,,,,,1024526
47267,1,2,21102022,1217,852,521020,02031952,470,2,1,...,,,,,,,,,,1024527
47268,1,2,01112022,2030,852,520400,12061945,477,2,4,...,,,,,,,,,,1024528
47269,1,2,23102022,0640,852,520490,07051932,490,2,4,...,,,,,,,,,,1024529

----------------------------------------------------
# Fazendo download para o computador

Primeiro arquivo da pasta DOGO2022.parquet:

In [ ]:
df1 = pd.read_parquet('/root/pysus/DOGO2022.parquet/674908bbbb854890842293409d69ff1b-0.parquet')
# Endereço de onde o arquivo é salvo na raiz do google colab

In [ ]:
df1

,ORIGEM,TIPOBITO,DTOBITO,HORAOBITO,NATURAL,CODMUNNATU,DTNASC,IDADE,SEXO,RACACOR,...,FONTES,TPRESGINFO,TPNIVELINV,NUDIASINF,DTCADINF,MORTEPARTO,DTCONCASO,FONTESINF,ALTCAUSA,CONTADOR
0,1,2,02112022,0350,822,220170,20101940,482,1,4,...,,,,,,,,,,1024530
1,1,2,30112022,0415,831,311370,09041939,483,2,1,...,,,,,,,,,,1024531
2,1,2,23102022,1340,852,520870,15071972,450,1,4,...,,,,,,,,,,1024532
3,1,2,02112022,1421,835,350780,12101932,490,1,1,...,,,,,,,,,,1024533
4,1,2,30102022,1735,852,520870,18061962,460,1,4,...,,,,,,,,,,1024547
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17265,1,2,11102022,0120,852,521850,30101945,476,1,4,...,,,,,,,,,,1543786
17266,1,2,04102022,1645,829,290710,16091976,446,1,4,...,,,,,,,,,,1543787
17267,1,2,11102022,0340,829,292720,10061926,496,2,4,...,,,,,,,,,,1543788
17268,1,2,09102022,2309,852,521150,05081950,472,2,4,...,,,,,,,,,,1543789
17269,1,2,03102022,2300,835,352640,26071981,441,2,1,...,,,,,,,,,,1543790

In [ ]:
# Salvando o arquivo localmente no ambiente do Colab
# o arquivo é salvo no sistema de arquivos temporário do Colab, dentro do diretório padrão /content.
df1.to_csv('SIM1.csv', index=True)

In [ ]:
# Fazendo download para o computador
from google.colab import files
files.download('/content/SIM1.csv')

----------------------------------------------------

Segundo arquivo da pasta DOGO2022.parquet:

In [ ]:
df2 = pd.read_parquet('/root/pysus/DOGO2022.parquet/eca3c827d1344672a689558e0a3e7eed-0.parquet')

In [ ]:
df2

,ORIGEM,TIPOBITO,DTOBITO,HORAOBITO,NATURAL,CODMUNNATU,DTNASC,IDADE,SEXO,RACACOR,...,FONTES,TPRESGINFO,TPNIVELINV,NUDIASINF,DTCADINF,MORTEPARTO,DTCONCASO,FONTESINF,ALTCAUSA,CONTADOR
0,1,2,27012022,2330,822,220770,27061962,459,1,,...,,,,,,,,,,50
1,1,2,01012022,2325,831,314330,08111948,473,2,4,...,,,,,,,,,,52
2,1,2,24022022,0651,853,530010,27111984,437,2,1,...,,,M,,,,,,,93
3,1,2,16022022,1053,829,290390,02111968,453,2,4,...,,,,,,,,,,235
4,1,2,24022022,1023,835,355030,13102015,406,1,4,...,,,,,,,,,,240
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,1,2,27112022,0002,822,220360,15061937,485,2,4,...,,,,,,,,,,1024525
29996,1,2,20102022,2100,852,521740,28011950,472,1,1,...,,,,,,,,,,1024526
29997,1,2,21102022,1217,852,521020,02031952,470,2,1,...,,,,,,,,,,1024527
29998,1,2,01112022,2030,852,520400,12061945,477,2,4,...,,,,,,,,,,1024528
29999,1,2,23102022,0640,852,520490,07051932,490,2,4,...,,,,,,,,,,1024529

In [ ]:
# Salvando o arquivo localmente no ambiente do Colab
# o arquivo é salvo no sistema de arquivos temporário do Colab, dentro do diretório padrão /content.
df2.to_csv('SIM2.csv', index=True)

In [ ]:
# Fazendo download para o computador
from google.colab import files
files.download('/content/SIM2.csv')

---------------------------
--------------------------
CÓDIGO AGRUPADO:

In [ ]:
# LIMPA ARQUIVOS DE EXECUÇÕES ANTERIORES
import shutil
import os

# Caminho da pasta
caminho_pasta = '/root/pysus'

# Verificar se a pasta existe antes de apagar
if os.path.exists(caminho_pasta):
    shutil.rmtree(caminho_pasta)  # Remove a pasta inteira
    print(f"A pasta {caminho_pasta} foi apagada.")
else:
    print("A pasta já está apagada. Siga em diante.")

A pasta /root/pysus foi apagada.

In [ ]:
# Instalando as bibliotecas:
!pip install -U git+https://github.com/AlertaDengue/PySUS.git    # instala a versão mais recente
!pip install pysus

from pysus import SIM
import pandas as pd
from pandas import DataFrame
from pandas import concat


# SIM FTP Database
sim = SIM().load() # Loads the files from DATASUS
sim.metadata
sim.paths

Collecting git+https://github.com/AlertaDengue/PySUS.git
  Cloning https://github.com/AlertaDengue/PySUS.git to /tmp/pip-req-build-jnwjb9d6
  Running command git clone --filter=blob:none --quiet https://github.com/AlertaDengue/PySUS.git /tmp/pip-req-build-jnwjb9d6
  Resolved https://github.com/AlertaDengue/PySUS.git to commit 54f7800db4da5171d55e3446d638d64beeb8b149
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting Unidecode<2.0.0,>=1.3.6 (from pysus==0.15.0)
  Downloading Unidecode-1.3.8-py3-none-any.whl.metadata (13 kB)
Collecting aioftp<0.22.0,>=0.21.4 (from pysus==0.15.0)
  Downloading aioftp-0.21.4-py3-none-any.whl.metadata (6.1 kB)
Collecting bigtree<0.13.0,>=0.12.2 (from pysus==0.15.0)
  Downloading bigtree-0.12.5-py3-none-any.whl.metadata (28 kB)
Collecting cffi==1.15.1 (from pysus==0.15.0)
  Downloading cffi-1.15.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.1 kB)
Collecting dateparser<2.0.0,>=1.1.8 (from pysus==0.15.0)
  Downloading dateparser-1.2.0-py2.py3-none-any.whl.metadata (28 kB)
Collecting dbfread==2.0.7 (from pysus==0.15.0)
  Downloading dbfread-2.0.7-py2.py3-none-any.whl.metadata (3.3 kB)
Collecting elasticsearch==7.16.2 (from elasticsearch[preprocessing]==7.16.2->pysus==0.15.0)
  Downloading elasticsearch-7.16.2-py2.py3-none-any.whl.metadata (5.7 kB)
Collecting fastparquet>=2023.10.1 (from pysus==0.15.0)
  Downloading fastparquet-2024.11.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.2 kB)
Requirement already satisfied: humanize<5.0.0,>=4.8.0 in /usr/local/lib/python3.10/dist-packages (from pysus==0.15.0) (4.11.0)
Collecting loguru<0.7.0,>=0.6.0 (from pysus==0.15.0)
  Downloading loguru-0.6.0-py3-none-any.whl.metadata (21 kB)
Collecting numpy==1.26.2 (from pysus==0.15.0)
  Downloading numpy-1.26.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.2/61.2 kB 4.3 MB/s eta 0:00:00
Requirement already satisfied: pandas<3.0.0,>=2.2.2 in /usr/local/lib/python3.10/dist-packages (from pysus==0.15.0) (2.2.2)
Requirement already satisfied: pyarrow>=11.0.0 in /usr/local/lib/python3.10/dist-packages (from pysus==0.15.0) (17.0.0)
Collecting pycparser==2.21 (from pysus==0.15.0)
  Downloading pycparser-2.21-py2.py3-none-any.whl.metadata (1.1 kB)
Collecting pyreaddbc>=1.1.0 (from pysus==0.15.0)
  Downloading pyreaddbc-1.2.0.tar.gz (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.7/57.7 kB 2.5 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: python-dateutil==2.8.2 in /usr/local/lib/python3.10/dist-packages (from pysus==0.15.0) (2.8.2)
Collecting tqdm==4.64.0 (from pysus==0.15.0)
  Downloading tqdm-4.64.0-py2.py3-none-any.whl.metadata (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.3/57.3 kB 4.1 MB/s eta 0:00:00
Requirement already satisfied: typing-extensions<5.0.0,>=4.9.0 in /usr/local/lib/python3.10/dist-packages (from pysus==0.15.0) (4.12.2)
Collecting urwid<3.0.0,>=2.1.2 (from pysus==0.15.0)
  Downloading urwid-2.6.16-py3-none-any.whl.metadata (11 kB)
Collecting wget<4.0,>=3.2 (from pysus==0.15.0)
  Downloading wget-3.2.zip (10 kB)
  Preparing metadata (setup.py) ... done
Collecting urllib3<2,>=1.21.1 (from elasticsearch==7.16.2->elasticsearch[preprocessing]==7.16.2->pysus==0.15.0)
  Downloading urllib3-1.26.20-py2.py3-none-any.whl.metadata (50 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.1/50.1 kB 2.9 MB/s eta 0:00:00
Requirement already satisfied: certifi in /usr/local/lib/python3.10/dist-packages (from elasticsearch==7.16.2->elasticsearch[preprocessing]==7.16.2->pysus==0.15.0) (2024.8.30)
WARNING: elasticsearch 7.16.2 does not provide the extra 'preprocessing'
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil==2.8.2->pysus==0.15.0) (1.16.0)
Requirement already satisfied: pytz in /usr/local/lib/python3.10/dist-packages (from dateparser<2.0.0,>=1.1.8->pysus==0.15.0) (2024.2)
Requirement already satisfied: regex!=2019.02.19,!=2021.8.27 in /usr/local/lib/python3.10/dist-packages (from dateparser<2.0.0,>=1.1.8->pysus==0.15.0) (2024.9.11)
Requirement already satisfied: tzlocal in /usr/local/lib/python3.10/dist-packages (from dateparser<2.0.0,>=1.1.8->pysus==0.15.0) (5.2)
Collecting cramjam>=2.3 (from fastparquet>=2023.10.1->pysus==0.15.0)
  Downloading cramjam-2.9.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from fastparquet>=2023.10.1->pysus==0.15.0) (2024.10.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from fastparquet>=2023.10.1->pysus==0.15.0) (24.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas<3.0.0,>=2.2.2->pysus==0.15.0) (2024.2)
Requirement already satisfied: pyyaml>=6 in /usr/local/lib/python3.10/dist-packages (from pyreaddbc>=1.1.0->pysus==0.15.0) (6.0.2)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.10/dist-packages (from urwid<3.0.0,>=2.1.2->pysus==0.15.0) (0.2.13)
Downloading cffi-1.15.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (441 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 441.8/441.8 kB 12.1 MB/s eta 0:00:00
Downloading dbfread-2.0.7-py2.py3-none-any.whl (20 kB)
Downloading elasticsearch-7.16.2-py2.py3-none-any.whl (385 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 385.7/385.7 kB 23.7 MB/s eta 0:00:00
Downloading numpy-1.26.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.2/18.2 MB 84.6 MB/s eta 0:00:00
Downloading pycparser-2.21-py2.py3-none-any.whl (118 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 118.7/118.7 kB 9.7 MB/s eta 0:00:00
Downloading tqdm-4.64.0-py2.py3-none-any.whl (78 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.4/78.4 kB 5.9 MB/s eta 0:00:00
Downloading aioftp-0.21.4-py3-none-any.whl (37 kB)
Downloading bigtree-0.12.5-py3-none-any.whl (63 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.5/63.5 kB 4.7 MB/s eta 0:00:00
Downloading dateparser-1.2.0-py2.py3-none-any.whl (294 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 295.0/295.0 kB 21.3 MB/s eta 0:00:00
Downloading fastparquet-2024.11.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 62.9 MB/s eta 0:00:00
Downloading loguru-0.6.0-py3-none-any.whl (58 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.3/58.3 kB 4.7 MB/s eta 0:00:00
Downloading Unidecode-1.3.8-py3-none-any.whl (235 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 235.5/235.5 kB 16.4 MB/s eta 0:00:00
Downloading urwid-2.6.16-py3-none-any.whl (297 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 297.2/297.2 kB 21.2 MB/s eta 0:00:00
Downloading cramjam-2.9.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 66.0 MB/s eta 0:00:00
Downloading urllib3-1.26.20-py2.py3-none-any.whl (144 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 144.2/144.2 kB 10.4 MB/s eta 0:00:00
Building wheels for collected packages: pysus, pyreaddbc, wget
  Building wheel for pysus (pyproject.toml) ... done
  Created wheel for pysus: filename=pysus-0.15.0-py3-none-any.whl size=1431968 sha256=818bf6108209805ed6f823bfb214202942e0a1d5b8de93f8c63b5a9a17e793d8
  Stored in directory: /tmp/pip-ephem-wheel-cache-l1atueqc/wheels/8a/d7/46/e8ca0ed9954b00155b8607fb9bef33a7e381b8f144a471a849
  Building wheel for pyreaddbc (pyproject.toml) ... done
  Created wheel for pyreaddbc: filename=pyreaddbc-1.2.0-cp310-cp310-manylinux_2_35_x86_64.whl size=89799 sha256=f7551d8d2624d2978143148178e0be2c44bd55c6612e11846bfd09975e34854f
  Stored in directory: /root/.cache/pip/wheels/44/9c/3c/0b2efbb6180556cf083065c5c0368bb38a26c83dbd5f9a9ba1
  Building wheel for wget (setup.py) ... done
  Created wheel for wget: filename=wget-3.2-py3-none-any.whl size=9656 sha256=13f583ab75172cc16195830609d1291518f4e7793f022ba2da9bb16ff2091842
  Stored in directory: /root/.cache/pip/wheels/8b/f1/7f/5c94f0a7a505ca1c81cd1d9208ae2064675d97582078e6c769
Successfully built pysus pyreaddbc wget
Installing collected packages: wget, dbfread, urwid, urllib3, Unidecode, tqdm, pycparser, numpy, loguru, cramjam, bigtree, aioftp, elasticsearch, dateparser, cffi, pyreaddbc, fastparquet, pysus
  Attempting uninstall: urllib3
    Found existing installation: urllib3 2.2.3
    Uninstalling urllib3-2.2.3:
      Successfully uninstalled urllib3-2.2.3
  Attempting uninstall: tqdm
    Found existing installation: tqdm 4.66.6
    Uninstalling tqdm-4.66.6:
      Successfully uninstalled tqdm-4.66.6
  Attempting uninstall: pycparser
    Found existing installation: pycparser 2.22
    Uninstalling pycparser-2.22:
      Successfully uninstalled pycparser-2.22
  Attempting uninstall: numpy
    Found existing installation: numpy 1.26.4
    Uninstalling numpy-1.26.4:
      Successfully uninstalled numpy-1.26.4
  Attempting uninstall: cffi
    Found existing installation: cffi 1.17.1
    Uninstalling cffi-1.17.1:
      Successfully uninstalled cffi-1.17.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
dopamine-rl 4.0.9 requires tqdm>=4.64.1, but you have tqdm 4.64.0 which is incompatible.
pygit2 1.16.0 requires cffi>=1.17.0, but you have cffi 1.15.1 which is incompatible.
Successfully installed Unidecode-1.3.8 aioftp-0.21.4 bigtree-0.12.5 cffi-1.15.1 cramjam-2.9.0 dateparser-1.2.0 dbfread-2.0.7 elasticsearch-7.16.2 fastparquet-2024.11.0 loguru-0.6.0 numpy-1.26.2 pycparser-2.21 pyreaddbc-1.2.0 pysus-0.15.0 tqdm-4.64.0 urllib3-1.26.20 urwid-2.6.16 wget-3.2
Requirement already satisfied: pysus in /usr/local/lib/python3.10/dist-packages (0.15.0)
Requirement already satisfied: Unidecode<2.0.0,>=1.3.6 in /usr/local/lib/python3.10/dist-packages (from pysus) (1.3.8)
Requirement already satisfied: aioftp<0.22.0,>=0.21.4 in /usr/local/lib/python3.10/dist-packages (from pysus) (0.21.4)
Requirement already satisfied: bigtree<0.13.0,>=0.12.2 in /usr/local/lib/python3.10/dist-packages (from pysus) (0.12.5)
Requirement already satisfied: cffi==1.15.1 in /usr/local/lib/python3.10/dist-packages (from pysus) (1.15.1)
Requirement already satisfied: dateparser<2.0.0,>=1.1.8 in /usr/local/lib/python3.10/dist-packages (from pysus) (1.2.0)
Requirement already satisfied: dbfread==2.0.7 in /usr/local/lib/python3.10/dist-packages (from pysus) (2.0.7)
Requirement already satisfied: elasticsearch==7.16.2 in /usr/local/lib/python3.10/dist-packages (from elasticsearch[preprocessing]==7.16.2->pysus) (7.16.2)
Requirement already satisfied: fastparquet>=2023.10.1 in /usr/local/lib/python3.10/dist-packages (from pysus) (2024.11.0)
Requirement already satisfied: humanize<5.0.0,>=4.8.0 in /usr/local/lib/python3.10/dist-packages (from pysus) (4.11.0)
Requirement already satisfied: loguru<0.7.0,>=0.6.0 in /usr/local/lib/python3.10/dist-packages (from pysus) (0.6.0)
Requirement already satisfied: numpy==1.26.2 in /usr/local/lib/python3.10/dist-packages (from pysus) (1.26.2)
Requirement already satisfied: pandas<3.0.0,>=2.2.2 in /usr/local/lib/python3.10/dist-packages (from pysus) (2.2.2)
Requirement already satisfied: pyarrow>=11.0.0 in /usr/local/lib/python3.10/dist-packages (from pysus) (17.0.0)
Requirement already satisfied: pycparser==2.21 in /usr/local/lib/python3.10/dist-packages (from pysus) (2.21)
Requirement already satisfied: pyreaddbc>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from pysus) (1.2.0)
Requirement already satisfied: python-dateutil==2.8.2 in /usr/local/lib/python3.10/dist-packages (from pysus) (2.8.2)
Requirement already satisfied: tqdm==4.64.0 in /usr/local/lib/python3.10/dist-packages (from pysus) (4.64.0)
Requirement already satisfied: typing-extensions<5.0.0,>=4.9.0 in /usr/local/lib/python3.10/dist-packages (from pysus) (4.12.2)
Requirement already satisfied: urwid<3.0.0,>=2.1.2 in /usr/local/lib/python3.10/dist-packages (from pysus) (2.6.16)
Requirement already satisfied: wget<4.0,>=3.2 in /usr/local/lib/python3.10/dist-packages (from pysus) (3.2)
Requirement already satisfied: urllib3<2,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from elasticsearch==7.16.2->elasticsearch[preprocessing]==7.16.2->pysus) (1.26.20)
Requirement already satisfied: certifi in /usr/local/lib/python3.10/dist-packages (from elasticsearch==7.16.2->elasticsearch[preprocessing]==7.16.2->pysus) (2024.8.30)
WARNING: elasticsearch 7.16.2 does not provide the extra 'preprocessing'
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil==2.8.2->pysus) (1.16.0)
Requirement already satisfied: pytz in /usr/local/lib/python3.10/dist-packages (from dateparser<2.0.0,>=1.1.8->pysus) (2024.2)
Requirement already satisfied: regex!=2019.02.19,!=2021.8.27 in /usr/local/lib/python3.10/dist-packages (from dateparser<2.0.0,>=1.1.8->pysus) (2024.9.11)
Requirement already satisfied: tzlocal in /usr/local/lib/python3.10/dist-packages (from dateparser<2.0.0,>=1.1.8->pysus) (5.2)
Requirement already satisfied: cramjam>=2.3 in /usr/local/lib/python3.10/dist-packages (from fastparquet>=2023.10.1->pysus) (2.9.0)
Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from fastparquet>=2023.10.1->pysus) (2024.10.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from fastparquet>=2023.10.1->pysus) (24.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas<3.0.0,>=2.2.2->pysus) (2024.2)
Requirement already satisfied: pyyaml>=6 in /usr/local/lib/python3.10/dist-packages (from pyreaddbc>=1.1.0->pysus) (6.0.2)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.10/dist-packages (from urwid<3.0.0,>=2.1.2->pysus) (0.2.13)

(/dissemin/publicos/SIM/CID10/DORES, /dissemin/publicos/SIM/CID9/DORES)

In [ ]:
sim.groups

{'CID10': 'DO', 'CID9': 'DOR'}

Dados até 1995 só podem ser recuperados pela CID-9.

Dados de 1996 em diante só podem ser recuperados pela CID-10.

-----------------------

EDITE CONFORME SUA NECESIDADE:

In [ ]:
# Sistema = ["SIM"]

In [ ]:
my_group = ["CID10"]      # Para dois: ["CID9","CID10"], etc...
my_state = ["GO"]       # Para dois: ["GO","SP"], etc...
my_year = [2022]        # Para dois: [2021, 2022], etc...

In [ ]:
# Pegando arquivos específicos:
arquivos = sim.get_files(my_group, uf=my_state, year=my_year)
## arquivos = sim.get_files("CID10", uf=["SP", "RJ"], year=[2019, 2020, 2021])
arquivos

[DOGO2022.dbc]

In [ ]:

for d in range(len(arquivos)):
  arquivos[d]
  sim.describe(arquivos[d])


  # Downloading files
  parquet_list = sim.download(arquivos[d])    # localizado no google colab, na pasta root/root/pysus/.

  if type(parquet_list)!=list:        # Se parquet_list não for uma lista, transforma em lista.
    parquet_list = [parquet_list]     # transforma em lista para poder utilizar o "for" abaixo, padrão para todos os códigos gerados.

# -----------------------------------------

  for j in range(len(parquet_list)):
# for parquet in parquet_list:
  # Reading files
    parquet_list[j].to_dataframe()

  #------------
  # Fazendo download para o computador
  import os

  # Listar arquivos no diretório atual
  lista_arquivos = os.listdir(f'{parquet_list[j]}')
  #print(f"Arquivos em {parquet_list}:", lista_arquivos)

  from google.colab import files

# O 'for' foi dividido em 3 devido a falhas ao baixar os arquivos com muitos dados. Alguns não estavam sendo baixados.
# Se a falha persistir ao baixar os arquivos para o computador, baixe-os diretamente em: '/root/pysus/'
  for i in range(len(lista_arquivos)):
    df = pd.read_parquet(f'{parquet_list[j]}/{lista_arquivos[i]}')
    df.to_csv(f'{parquet_list[j]}/SIH_{d}_{j}_{i}.csv', index=True)
    # files.download(f'{parquet_list[j]}/SIH_{d}_{j}_{i}.csv') # Fazendo download para o computador
    # files.download(f'{parquet_list[j]}/{lista_arquivos[i]}') # Fazendo download para o computador

  for i in range(len(lista_arquivos)):
    # df = pd.read_parquet(f'{parquet_list[j]}/{lista_arquivos[i]}')
    # df.to_csv(f'{parquet_list[j]}/SIH_{d}_{j}_{i}.csv', index=True)
    files.download(f'{parquet_list[j]}/SIH_{d}_{j}_{i}.csv') # Fazendo download para o computador
    # files.download(f'{parquet_list[j]}/{lista_arquivos[i]}') # Fazendo download para o computador

  for i in range(len(lista_arquivos)):
    # df = pd.read_parquet(f'{parquet_list[j]}/{lista_arquivos[i]}')
    # df.to_csv(f'{parquet_list[j]}/SIH_{d}_{j}_{i}.csv', index=True)
    # files.download(f'{parquet_list[j]}/SIH_{d}_{j}_{i}.csv') # Fazendo download para o computador
    files.download(f'{parquet_list[j]}/{lista_arquivos[i]}') # Fazendo download para o computador

DOGO2022.parquet: 100%|██████████| 116k/116k [00:06<00:00, 16.7kB/s]

OS ARQUIVOS TAMBÉM PODEM SER ACESSADOS EM '/root/pysus/', PASTA RAIZ DO GOOGLE COLAB.